package plcdata

// GetEventBitDefinitions retorna todas as definições dos bits de eventos
func GetEventBitDefinitions() *EventBitsStructure {
	return &EventBitsStructure{
		// ENCHIMENTO EVENTOS - Words 48, 49, 50 (Bits 768-815)
		Enchimento: []StatusBitDefinition{
			// Word 48 (Bits 768-783)
			{Name: "ORDEM_LOCAL_FECHO_COMPORTAS", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 0, Description: "ORDEM LOCAL FECHO COMPORTAS"},
			{Name: "ORDEM_LOCAL_PARAGEM_COMPORTAS", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 1, Description: "ORDEM LOCAL PARAGEM COMPORTAS"},
			{Name: "CONDICAO_PORTA_JUSANTE_FECHADA_PRESENTE", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 2, Description: "CONDIÇÃO PORTA JUSANTE FECHADA PRESENTE"},
			{Name: "CONDICAO_CIRCUITO_ESVAZIAMENTO_FECHADO_PRESENTE", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 3, Description: "CONDIÇÃO CIRCUITO ESVAZIAMENTO FECHADO PRESENTE"},
			{Name: "COMPORTA_A_DIREITA_ABERTA_TEMPO_ABERT", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 4, Description: "COMPORTA A DIREITA ABERTA TEMPO ABERT."},
			{Name: "COMPORTA_A_DIREITA_POSICAO_ESTABILIZACAO_TEMPO_ABERT", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 5, Description: "COMPORTA A DIREITA NA POSIÇÃO DE ESTABILIZAÇÃO TEMPO ABERT."},
			{Name: "COMPORTA_A_DIREITA_FECHADA_TEMPO_FECHO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 6, Description: "COMPORTA A DIREITA FECHADA TEMPO FECHO"},
			{Name: "COMPORTA_B_ESQUERDA_ABERTA_TEMPO_ABERT", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 7, Description: "COMPORTA B ESQUERDA ABERTA TEMPO ABERT."},
			{Name: "BOTAO_ACEITACAO_AVARIAS_PREMIDO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 8, Description: "BOTÃO ACEITAÇÃO DE AVARIAS PREMIDO"},
			{Name: "SISTEMA_EM_MANUAL", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 9, Description: "SISTEMA EM MANUAL"},
			{Name: "SISTEMA_EM_AUTOMATICO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 10, Description: "SISTEMA EM AUTOMATICO"},
			{Name: "SISTEMA_DESLIGADO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 11, Description: "SISTEMA DESLIGADO"},
			{Name: "ORDEM_REMOTA_ABERTURA_COMPORTAS", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 12, Description: "ORDEM REMOTA ABERTURA COMPORTAS"},
			{Name: "ORDEM_REMOTA_FECHO_COMPORTAS", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 13, Description: "ORDEM REMOTA FECHO COMPORTAS"},
			{Name: "ORDEM_REMOTA_PARAGEM_COMPORTAS", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 14, Description: "ORDEM REMOTA DE PARAGEM COMPORTAS"},
			{Name: "ORDEM_LOCAL_ABERTURA_COMPORTAS", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 48, BitIndex: 15, Description: "ORDEM LOCAL ABERTURA COMPORTAS"},

			// Word 49 (Bits 784-799)
			{Name: "COMPORTA_A_DIREITA_SELECIONADA_REMOTO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 0, Description: "COMPORTA A DIREITA SELECIONADA REMOTO"},
			{Name: "COMPORTA_B_ESQUERDA_SELECIONADA_REMOTO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 1, Description: "COMPORTA B ESQUERDA SELECIONADA REMOTO"},
			{Name: "COMPORTA_A_DIREITA_A_ABRIR_AUTOMATICO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 2, Description: "COMPORTA A DIREITA A ABRIR - AUTOMATICO"},
			{Name: "COMPORTA_B_ESQUERDA_A_ABRIR_AUTOMATICO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 3, Description: "COMPORTA B ESQUERDA A ABRIR - AUTOMATICO"},
			{Name: "COMPORTA_A_DIREITA_A_ABRIR_SUBIDA_RAPIDA_AUTOMATICO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 4, Description: "COMPORTA A DIREITA A ABRIR SUBIDA RAPIDA - AUTOMATICO"},
			{Name: "COMPORTA_B_ESQUERDA_A_ABRIR_SUBIDA_RAPIDA_AUTOMATICO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 5, Description: "COMPORTA B ESQUERDA A ABRIR SUBIDA RAPIDA - AUTOMATICO"},
			{Name: "COMPORTA_A_DIREITA_A_FECHAR_AUTOMATICO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 6, Description: "COMPORTA A DIREITA A FECHAR - AUTOMATICO"},
			{Name: "COMPORTA_B_ESQUERDA_A_FECHAR_AUTOMATICO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 7, Description: "COMPORTA B ESQUERDA A FECHAR - AUTOMATICO"},
			{Name: "COMPORTA_B_ESQUERDA_POSICAO_ESTABILIZACAO_TEMPO_ABERT", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 8, Description: "COMPORTA B ESQUERDA NA POSIÇÃO DE ESTABILIZAÇÃO TEMPO ABERT."},
			{Name: "COMPORTA_B_ESQUERDA_FECHADA_TEMPO_FECHO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 9, Description: "COMPORTA B ESQUERDA FECHADA TEMPO FECHO"},
			{Name: "BOMBA_OLEO_COMPORTA_A_DIREITA_LIGADA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 10, Description: "BOMBA OLEO COMPORTA A DIREITA LIGADA"},
			{Name: "BOMBA_OLEO_COMPORTA_B_ESQUERDA_LIGADA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 11, Description: "BOMBA OLEO COMPORTA B ESQUERDA LIGADA"},
			{Name: "COMPORTA_A_DIREITA_A_FECHAR", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 12, Description: "COMPORTA A DIREITA A FECHAR"},
			{Name: "COMPORTA_B_ESQUERDA_A_FECHAR", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 13, Description: "COMPORTA B ESQUERDA A FECHAR"},
			{Name: "COMPORTA_A_DIREITA_SELECIONADA_LOCAL", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 14, Description: "COMPORTA A DIREITA SELECIONADA LOCAL"},
			{Name: "COMPORTA_B_ESQUERDA_SELECIONADA_LOCAL", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 49, BitIndex: 15, Description: "COMPORTA B ESQUERDA SELECIONADA LOCAL"},

			// Word 50 (Bits 800-815)
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 0, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 1, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 2, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 3, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 4, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 5, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 6, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 7, Description: "RESERVA"},
			{Name: "COMPORTAS_EM_PROGRAMA_LIMPEZA_PORTA_JUSANTE", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 8, Description: "COMPORTAS EM PROGRAMA DE LIMPEZA PORTA JUSANTE"},
			{Name: "COMPORTA_A_DIREITA_FORA_SERVICO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 9, Description: "COMPORTA A DIREITA FORA DE SERVIÇO"},
			{Name: "COMPORTA_B_ESQUERDA_FORA_SERVICO", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 10, Description: "COMPORTA B ESQUERDA FORA DE SERVIÇO"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 11, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 12, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 13, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 14, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ENCHIMENTO", WordIndex: 50, BitIndex: 15, Description: "RESERVA"},
		},

		// ESVAZIAMENTO EVENTOS - Words 51, 52, 53 (Bits 816-863)
		Esvaziamento: []StatusBitDefinition{
			// Word 51 (Bits 816-831)
			{Name: "ORDEM_LOCAL_FECHO_COMPORTAS", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 0, Description: "ORDEM LOCAL FECHO COMPORTAS"},
			{Name: "ORDEM_LOCAL_PARAGEM_COMPORTAS", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 1, Description: "ORDEM LOCAL PARAGEM COMPORTAS"},
			{Name: "CONDICAO_PORTA_MONTANTE_FECHADA_PRESENTE", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 2, Description: "CONDIÇÃO PORTA MONTANTE FECHADA PRESENTE"},
			{Name: "CONDICAO_CIRCUITO_ENCHIMENTO_FECHADO_PRESENTE", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 3, Description: "CONDIÇÃO CIRCUITO ENCHIMENTO FECHADO PRESENTE"},
			{Name: "COMPORTA_A_DIREITA_ABERTA_TEMPO_ABERT", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 4, Description: "COMPORTA A DIREITA ABERTA TEMPO ABERT."},
			{Name: "COMPORTA_A_DIREITA_POSICAO_ESTABILIZACAO_TEMPO_ABERT", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 5, Description: "COMPORTA A DIREITA NA POSIÇÃO DE ESTABILIZAÇÃO TEMPO ABERT."},
			{Name: "COMPORTA_A_DIREITA_FECHADA_TEMPO_FECHO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 6, Description: "COMPORTA A DIREITA FECHADA TEMPO FECHO"},
			{Name: "COMPORTA_B_ESQUERDA_ABERTA_TEMPO_ABERT", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 7, Description: "COMPORTA B ESQUERDA ABERTA TEMPO ABERT."},
			{Name: "BOTAO_ACEITACAO_AVARIAS_PREMIDO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 8, Description: "BOTÃO ACEITAÇÃO DE AVARIAS PREMIDO"},
			{Name: "SISTEMA_EM_MANUAL", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 9, Description: "SISTEMA EM MANUAL"},
			{Name: "SISTEMA_EM_AUTOMATICO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 10, Description: "SISTEMA EM AUTOMATICO"},
			{Name: "SISTEMA_DESLIGADO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 11, Description: "SISTEMA DESLIGADO"},
			{Name: "ORDEM_REMOTA_ABERTURA_COMPORTAS", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 12, Description: "ORDEM REMOTA ABERTURA COMPORTAS"},
			{Name: "ORDEM_REMOTA_FECHO_COMPORTAS", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 13, Description: "ORDEM REMOTA FECHO COMPORTAS"},
			{Name: "ORDEM_REMOTA_PARAGEM_COMPORTAS", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 14, Description: "ORDEM REMOTA DE PARAGEM COMPORTAS"},
			{Name: "ORDEM_LOCAL_ABERTURA_COMPORTAS", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 51, BitIndex: 15, Description: "ORDEM LOCAL ABERTURA COMPORTAS"},

			// Word 52 (Bits 832-847)
			{Name: "COMPORTA_A_DIREITA_SELECIONADA_REMOTO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 0, Description: "COMPORTA A DIREITA SELECIONADA REMOTO"},
			{Name: "COMPORTA_B_ESQUERDA_SELECIONADA_REMOTO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 1, Description: "COMPORTA B ESQUERDA SELECIONADA REMOTO"},
			{Name: "COMPORTA_A_DIREITA_A_ABRIR_AUTOMATICO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 2, Description: "COMPORTA A DIREITA A ABRIR - AUTOMATICO"},
			{Name: "COMPORTA_B_ESQUERDA_A_ABRIR_AUTOMATICO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 3, Description: "COMPORTA B ESQUERDA A ABRIR - AUTOMATICO"},
			{Name: "COMPORTA_A_DIREITA_A_ABRIR_SUBIDA_RAPIDA_AUTOMATICO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 4, Description: "COMPORTA A DIREITA A ABRIR SUBIDA RAPIDA - AUTOMATICO"},
			{Name: "COMPORTA_B_ESQUERDA_A_ABRIR_SUBIDA_RAPIDA_AUTOMATICO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 5, Description: "COMPORTA B ESQUERDA A ABRIR SUBIDA RAPIDA - AUTOMATICO"},
			{Name: "COMPORTA_A_DIREITA_A_FECHAR_AUTOMATICO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 6, Description: "COMPORTA A DIREITA A FECHAR - AUTOMATICO"},
			{Name: "COMPORTA_B_ESQUERDA_A_FECHAR_AUTOMATICO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 7, Description: "COMPORTA B ESQUERDA A FECHAR - AUTOMATICO"},
			{Name: "COMPORTA_B_ESQUERDA_POSICAO_ESTABILIZACAO_TEMPO_ABERT", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 8, Description: "COMPORTA B ESQUERDA NA POSIÇÃO DE ESTABILIZAÇÃO TEMPO ABERT."},
			{Name: "COMPORTA_B_ESQUERDA_FECHADA_TEMPO_FECHO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 9, Description: "COMPORTA B ESQUERDA FECHADA TEMPO FECHO"},
			{Name: "BOMBA_OLEO_COMPORTA_A_DIREITA_LIGADA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 10, Description: "BOMBA OLEO COMPORTA A DIREITA LIGADA"},
			{Name: "BOMBA_OLEO_COMPORTA_B_ESQUERDA_LIGADA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 11, Description: "BOMBA OLEO COMPORTA B ESQUERDA LIGADA"},
			{Name: "COMPORTA_A_DIREITA_A_FECHAR", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 12, Description: "COMPORTA A DIREITA A FECHAR"},
			{Name: "COMPORTA_B_ESQUERDA_A_FECHAR", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 13, Description: "COMPORTA B ESQUERDA A FECHAR"},
			{Name: "COMPORTA_A_DIREITA_SELECIONADA_LOCAL", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 14, Description: "COMPORTA A DIREITA SELECIONADA LOCAL"},
			{Name: "COMPORTA_B_ESQUERDA_SELECIONADA_LOCAL", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 52, BitIndex: 15, Description: "COMPORTA B ESQUERDA SELECIONADA LOCAL"},

			// Word 53 (Bits 848-863)
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 0, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 1, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 2, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 3, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 4, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 5, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 6, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 7, Description: "RESERVA"},
			{Name: "COMPORTAS_EM_PROGRAMA_LIMPEZA_PORTA_JUSANTE", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 8, Description: "COMPORTAS EM PROGRAMA DE LIMPEZA PORTA JUSANTE"},
			{Name: "COMPORTA_A_DIREITA_FORA_SERVICO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 9, Description: "COMPORTA A DIREITA FORA DE SERVIÇO"},
			{Name: "COMPORTA_B_ESQUERDA_FORA_SERVICO", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 10, Description: "COMPORTA B ESQUERDA FORA DE SERVIÇO"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 11, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 12, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 13, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 14, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESVAZIAMENTO", WordIndex: 53, BitIndex: 15, Description: "RESERVA"},
		},

		// PORTA JUSANTE EVENTOS - Words 54, 55 (Bits 864-895)
		PortaJusante: []StatusBitDefinition{
			// Word 54 (Bits 864-879)
			{Name: "ORDEM_PARAGEM_BOTONEIRA_QUADRO_COMANDO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 0, Description: "ORDEM DE PARAGEM BOTONEIRA QUADRO DE COMANDO"},
			{Name: "ORDEM_PARAGEM_BOTONEIRA_LOCAL_MARGEM_ESQUERDA", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 1, Description: "ORDEM DE PARAGEM BOTONEIRA LOCAL MARGEM ESQUERDA"},
			{Name: "PORTA_ABERTA_SUBIDA_FIM_CURSO_POS_DIR", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 2, Description: "PORTA ABERTA (SUBIDA) - FIM DE CURSO. POS.DIR"},
			{Name: "PORTA_ABERTA_SUBIDA_POSICAO_POS_DIR", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 3, Description: "PORTA ABERTA (SUBIDA) - POSIÇÃO. POS.DIR"},
			{Name: "PORTA_FECHADA_DESCIDA_FIM_CURSO_POS_DIR", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 4, Description: "PORTA FECHADA (DESCIDA) - FIM DE CURSO POS.DIR"},
			{Name: "PORTA_FECHADA_DESCIDA_POSICAO_POS_DIR", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 5, Description: "PORTA FECHADA (DESCIDA) - POSIÇÃO. POS.DIR"},
			{Name: "ORDEM_PARAGEM_PORTA_SALA_COMANDO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 6, Description: "ORDEM DE PARAGEM DA PORTA - SALA DE COMANDO"},
			{Name: "ORDEM_ABERTURA_SUBIDA_PORTA_SALA_COMANDO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 7, Description: "ORDEM DE ABERTURA (SUBIDA) DA PORTA - SALA DE COMANDO"},
			{Name: "BOTAO_ACEITACAO_AVARIAS_PREMIDO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 8, Description: "BOTÃO ACEITAÇÃO DE AVARIAS PREMIDO"},
			{Name: "SISTEMA_EM_MANUAL", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 9, Description: "SISTEMA EM MANUAL"},
			{Name: "SISTEMA_EM_AUTOMATICO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 10, Description: "SISTEMA EM AUTOMATICO"},
			{Name: "SISTEMA_DESLIGADO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 11, Description: "SISTEMA DESLIGADO"},
			{Name: "ORDEM_ABERTURA_SUBIDA_PORTA_BOTONEIRA_LOCAL", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 12, Description: "ORDEM DE ABERTURA (SUBIDA) DA PORTA POR BOTONEIRA LOCAL"},
			{Name: "ORDEM_FECHO_DESCIDA_PORTA_BOTONEIRA_LOCAL", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 13, Description: "ORDEM DE FECHO (DESCIDA) DA PORTA POR BOTONEIRA LOCAL"},
			{Name: "PRESENCA_BOTONEIRA_COMANDO_LOCAL", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 14, Description: "PRESENÇA DE BOTONEIRA DE COMANDO LOCAL"},
			{Name: "ORDEM_PARAGEM_BOTONEIRA_LOCAL_MARGEM_DIREITA", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 54, BitIndex: 15, Description: "ORDEM DE PARAGEM BOTONEIRA LOCAL MARGEM DIREITA"},

			// Word 55 (Bits 880-895)
			{Name: "NIVELAMENTO_PORTA_ATIVADO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 0, Description: "NIVELAMENTO DA PORTA ATIVADO"},
			{Name: "FREIO_SEGURANCA_DIREITO_FORCADO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 1, Description: "FREIO DE SEGURANÇA DIREITO FORÇADO"},
			{Name: "FREIO_MOTOR_DIREITO_FORCADO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 2, Description: "FREIO DO MOTOR DIREITO FORÇADO"},
			{Name: "FREIO_SEGURANCA_ESQUERDO_FORCADO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 3, Description: "FREIO DE SEGURANÇA ESQUERDO FORÇADO"},
			{Name: "FREIO_MOTOR_ESQUERDO_FORCADO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 4, Description: "FREIO DO MOTOR ESQUERDO FORÇADO"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 5, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 6, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 7, Description: "RESERVA"},
			{Name: "ORDEM_FECHO_DESCIDA_PORTA_SALA_COMANDO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 8, Description: "ORDEM DE FECHO (DESCIDA) DA PORTA - SALA DE COMANDO"},
			{Name: "CONDICOES_REMOTAS_ABERTURA_PRESENTES_IGUALDADE_NIVEIS", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 9, Description: "CONDIÇÕES REMOTAS DE ABERTURA PRESENTES (IGUALDADE DE NIVEIS)"},
			{Name: "PORTA_A_ABRIR_A_SUBIR", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 10, Description: "PORTA A ABRIR (A SUBIR)"},
			{Name: "PORTA_A_FECHAR_A_DESCER", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 11, Description: "PORTA A FECHAR (A DESCER)"},
			{Name: "PORTA_A_ABRIR_A_SUBIR_EM_AUTOMATICO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 12, Description: "PORTA A ABRIR (A SUBIR) EM AUTOMATICO"},
			{Name: "PORTA_A_FECHAR_A_DESCER_EM_AUTOMATICO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 13, Description: "PORTA A FECHAR (A DESCER) EM AUTOMATICO"},
			{Name: "ORDEM_ABERTURA_SUBIDA_PORTA_BOTONEIRA_QUADRO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 14, Description: "ORDEM DE ABERTURA (SUBIDA) DA PORTA POR BOTONEIRA DO QUADRO"},
			{Name: "ORDEM_FECHO_DESCIDA_PORTA_BOTONEIRA_QUADRO", Equipment: "RG_EVENTO_PORTAJUSANTE", WordIndex: 55, BitIndex: 15, Description: "ORDEM DE FECHO (DESCIDA) DA PORTA POR BOTONEIRA DO QUADRO"},
		},

		// PORTA MONTANTE EVENTOS - Words 56, 57 (Bits 896-927)
		PortaMontante: []StatusBitDefinition{
			// Word 56 (Bits 896-911)
			{Name: "ORDEM_PARAGEM_BOTONEIRA_QUADRO_COMANDO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 0, Description: "ORDEM DE PARAGEM BOTONEIRA QUADRO DE COMANDO"},
			{Name: "ORDEM_PARAGEM_BOTONEIRA_LOCAL_MARGEM_ESQUERDA", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 1, Description: "ORDEM DE PARAGEM BOTONEIRA LOCAL MARGEM ESQUERDA"},
			{Name: "PORTA_FECHADA_SUBIDA_FIM_CURSO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 2, Description: "PORTA FECHADA (SUBIDA) - FIM DE CURSO"},
			{Name: "PORTA_FECHADA_SUBIDA_POSICAO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 3, Description: "PORTA FECHADA (SUBIDA) - POSIÇÃO"},
			{Name: "PORTA_ABERTA_DESCIDA_FIM_CURSO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 4, Description: "PORTA ABERTA (DESCIDA) - FIM DE CURSO"},
			{Name: "PORTA_ABERTA_DESCIDA_POSICAO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 5, Description: "PORTA ABERTA (DESCIDA) - POSIÇÃO"},
			{Name: "ORDEM_PARAGEM_PORTA_SALA_COMANDO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 6, Description: "ORDEM DE PARAGEM DA PORTA - SALA DE COMANDO"},
			{Name: "ORDEM_FECHO_SUBIDA_PORTA_SALA_COMANDO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 7, Description: "ORDEM DE FECHO (SUBIDA) DA PORTA - SALA DE COMANDO"},
			{Name: "BOTAO_ACEITACAO_AVARIAS_PREMIDO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 8, Description: "BOTÃO ACEITAÇÃO DE AVARIAS PREMIDO"},
			{Name: "SISTEMA_EM_MANUAL", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 9, Description: "SISTEMA EM MANUAL"},
			{Name: "SISTEMA_EM_AUTOMATICO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 10, Description: "SISTEMA EM AUTOMATICO"},
			{Name: "SISTEMA_DESLIGADO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 11, Description: "SISTEMA DESLIGADO"},
			{Name: "ORDEM_FECHO_SUBIDA_PORTA_BOTONEIRA_LOCAL", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 12, Description: "ORDEM DE FECHO (SUBIDA) DA PORTA POR BOTONEIRA LOCAL"},
			{Name: "ORDEM_ABERTURA_DESCIDA_PORTA_BOTONEIRA_LOCAL", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 13, Description: "ORDEM DE ABERTURA (DESCIDA) DA PORTA POR BOTONEIRA LOCAL"},
			{Name: "PRESENCA_BOTONEIRA_COMANDO_LOCAL", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 14, Description: "PRESENÇA DE BOTONEIRA DE COMANDO LOCAL"},
			{Name: "ORDEM_PARAGEM_BOTONEIRA_LOCAL_MARGEM_DIREITA", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 56, BitIndex: 15, Description: "ORDEM DE PARAGEM BOTONEIRA LOCAL MARGEM DIREITA"},

			// Word 57 (Bits 912-927)
			{Name: "NIVELAMENTO_PORTA_ATIVADO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 0, Description: "NIVELAMENTO DA PORTA ATIVADO"},
			{Name: "FREIO_SEGURANCA_DIREITO_FORCADO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 1, Description: "FREIO DE SEGURANÇA DIREITO FORÇADO"},
			{Name: "FREIO_MOTOR_DIREITO_FORCADO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 2, Description: "FREIO DO MOTOR DIREITO FORÇADO"},
			{Name: "FREIO_SEGURANCA_ESQUERDO_FORCADO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 3, Description: "FREIO DE SEGURANÇA ESQUERDO FORÇADO"},
			{Name: "FREIO_MOTOR_ESQUERDO_FORCADO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 4, Description: "FREIO DO MOTOR ESQUERDO FORÇADO"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 5, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 6, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 7, Description: "RESERVA"},
			{Name: "ORDEM_ABERTURA_DESCIDA_PORTA_SALA_COMANDO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 8, Description: "ORDEM DE ABERTURA (DESCIDA) DA PORTA - SALA DE COMANDO"},
			{Name: "CONDICOES_REMOTAS_ABERTURA_PRESENTES_IGUALDADE_NIVEIS", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 9, Description: "CONDIÇÕES REMOTAS DE ABERTURA PRESENTES (IGUALDADE DE NIVEIS)"},
			{Name: "PORTA_A_FECHAR_A_SUBIR", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 10, Description: "PORTA A FECHAR (A SUBIR)"},
			{Name: "PORTA_A_ABRIR_A_DESCER", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 11, Description: "PORTA A ABRIR (A DESCER)"},
			{Name: "PORTA_A_FECHAR_A_SUBIR_EM_AUTOMATICO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 12, Description: "PORTA A FECHAR (A SUBIR) EM AUTOMATICO"},
			{Name: "PORTA_A_ABRIR_A_DESCER_EM_AUTOMATICO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 13, Description: "PORTA A ABRIR (A DESCER) EM AUTOMATICO"},
			{Name: "ORDEM_FECHO_SUBIDA_PORTA_BOTONEIRA_QUADRO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 14, Description: "ORDEM DE FECHO (SUBIDA) DA PORTA POR BOTONEIRA DO QUADRO"},
			{Name: "ORDEM_ABERTURA_DESCIDA_PORTA_BOTONEIRA_QUADRO", Equipment: "RG_EVENTO_PORTAMONTANTE", WordIndex: 57, BitIndex: 15, Description: "ORDEM DE ABERTURA (DESCIDA) DA PORTA POR BOTONEIRA DO QUADRO"},
		},

		// COMANDO ECLUSA EVENTOS - Words 58, 59, 60 (Bits 928-975)
		ComandoEclusa: []StatusBitDefinition{
			// Word 58 (Bits 928-943)
			{Name: "SAIDA_ECLUSA_PARA_MONTANTE_AUTORIZADA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 0, Description: "SAÍDA ECLUSA PARA MONTANTE AUTORIZADA"},
			{Name: "ENTRADA_ECLUSA_POR_MONTANTE_INTERDITA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 1, Description: "ENTRADA ECLUSA POR MONTANTE INTERDITA"},
			{Name: "ENTRADA_ECLUSA_POR_MONTANTE_AUTORIZADA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 2, Description: "ENTRADA ECLUSA POR MONTANTE AUTORIZADA"},
			{Name: "ENTRADA_ECLUSA_POR_MONTANTE_EM_PREPARACAO", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 3, Description: "ENTRADA ECLUSA POR MONTANTE EM PREPARAÇÃO"},
			{Name: "SAIDA_ECLUSA_PARA_JUSANTE_INTERDITA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 4, Description: "SAÍDA ECLUSA PARA JUSANTE INTERDITA"},
			{Name: "SAIDA_ECLUSA_PARA_JUSANTE_AUTORIZADA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 5, Description: "SAÍDA ECLUSA PARA JUSANTE AUTORIZADA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 6, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 7, Description: "RESERVA"},
			{Name: "IGUALDADE_NIVEIS_UMN_MONTANTE_PRESENTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 8, Description: "IGUALDADE DE NIVEIS UMN A MONTANTE PRESENTE"},
			{Name: "IGUALDADE_NIVEIS_UMN_JUSANTE_PRESENTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 9, Description: "IGUALDADE DE NIVEIS UMN A JUSANTE PRESENTE"},
			{Name: "IGUALDADE_NIVEIS_SALA_COMANDO_MONTANTE_PRESENTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 10, Description: "IGUALDADE DE NIVEIS SALA DE COMANDO A MONTANTE PRESENTE"},
			{Name: "IGUALDADE_NIVEIS_SALA_COMANDO_JUSANTE_PRESENTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 11, Description: "IGUALDADE DE NIVEIS SALA DE COMANDO A JUSANTE PRESENTE"},
			{Name: "ENTRADA_ECLUSA_POR_JUSANTE_INTERDITA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 12, Description: "ENTRADA ECLUSA POR JUSANTE INTERDITA"},
			{Name: "ENTRADA_ECLUSA_POR_JUSANTE_AUTORIZADA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 13, Description: "ENTRADA ECLUSA POR JUSANTE AUTORIZADA"},
			{Name: "ENTRADA_ECLUSA_POR_JUSANTE_EM_PREPARACAO", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 14, Description: "ENTRADA ECLUSA POR JUSANTE EM PREPARAÇÃO"},
			{Name: "SAIDA_ECLUSA_PARA_MONTANTE_INTERDITA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 58, BitIndex: 15, Description: "SAÍDA ECLUSA PARA MONTANTE INTERDITA"},

			// Word 59 (Bits 944-959)
			{Name: "ECLUSAGEM_AUTOMATICA_SUBIDA_PREPARADA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 0, Description: "ECLUSAGEM AUTOMÁTICA DE SUBIDA PREPARADA"},
			{Name: "ECLUSAGEM_AUTOMATICA_SUBIDA_ATIVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 1, Description: "ECLUSAGEM AUTOMÁTICA DE SUBIDA ATIVA"},
			{Name: "ECLUSAGEM_AUTOMATICA_SUBIDA_CONCLUIDA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 2, Description: "ECLUSAGEM AUTOMÁTICA DE SUBIDA CONCLUIDA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 3, Description: "RESERVA"},
			{Name: "ECLUSAGEM_AUTOMATICA_DESCIDA_PREPARADA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 4, Description: "ECLUSAGEM AUTOMÁTICA DE DESCIDA PREPARADA"},
			{Name: "ECLUSAGEM_AUTOMATICA_DESCIDA_ATIVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 5, Description: "ECLUSAGEM AUTOMÁTICA DE DESCIDA ATIVA"},
			{Name: "ECLUSAGEM_AUTOMATICA_DESCIDA_CONCLUIDA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 6, Description: "ECLUSAGEM AUTOMÁTICA DE DESCIDA CONCLUIDA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 7, Description: "RESERVA"},
			{Name: "CAMARAS_DETECAO_BARCO_GRANDE_JUSANTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 8, Description: "CAMARAS - DETEÇÃO BARCO GRANDE A JUSANTE"},
			{Name: "CAMARAS_DETECAO_BARCO_PEQUENO_JUSANTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 9, Description: "CAMARAS - DETEÇÃO BARCO PEQUENO A JUSANTE"},
			{Name: "CAMARAS_DETECAO_BARCO_PEQUENO_MONTANTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 10, Description: "CAMARAS - DETEÇÃO BARCO PEQUENO A MONTANTE"},
			{Name: "CAMARAS_DETECAO_BARCO_GRANDE_MONTANTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 11, Description: "CAMARAS - DETEÇÃO BARCO GRANDE A MONTANTE"},
			{Name: "CAMARAS_DETECAO_BARCO_CALDEIRA_FORA_LIMITES_MONTANTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 12, Description: "CAMARAS - DETEÇÃO BARCO NA CALDEIRA FORA DOS LIMITES A MONTANTE"},
			{Name: "CAMARAS_DETECAO_BARCO_CALDEIRA_FORA_LIMITES_JUSANTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 13, Description: "CAMARAS - DETEÇÃO BARCO NA CALDEIRA FORA DOS LIMITES A JUSANTE"},
			{Name: "CAMARAS_DETECAO_BARCO_CALDEIRA_DURANTE_ECLUSAGEM_DESCIDA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 14, Description: "CAMARAS - DETEÇÃO BARCO NA CALDEIRA DURANTE ECLUSAGEM AUTOMÁTICA DE DESCIDA"},
			{Name: "CAMARAS_DETECAO_BARCO_CALDEIRA_DURANTE_ECLUSAGEM_SUBIDA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 59, BitIndex: 15, Description: "CAMARAS - DETEÇÃO BARCO NA CALDEIRA DURANTE ECLUSAGEM AUTOMÁTICA DE SUBIDA"},

			// Word 60 (Bits 960-975)
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 0, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 1, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 2, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 3, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 4, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 5, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 6, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 7, Description: "RESERVA"},
			{Name: "DETECAO_EXCESSO_VELOCIDADE_ENTRADA_MONTANTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 8, Description: "DETEÇÃO EXCESSO VELOCIDADE ENTRADA MONTANTE"},
			{Name: "DETECAO_EXCESSO_VELOCIDADE_CALDEIRA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 9, Description: "DETEÇÃO EXCESSO VELOCIDADE CALDEIRA"},
			{Name: "DETECAO_EXCESSO_VELOCIDADE_ENTRADA_JUSANTE", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 10, Description: "DETEÇÃO EXCESSO VELOCIDADE ENTRADA JUSANTE"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 11, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 12, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 13, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 14, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_COMANDO_ECLUSA", WordIndex: 60, BitIndex: 15, Description: "RESERVA"},
		},

		// ESGOTO/DRENAGEM EVENTOS - Words 61, 62 (Bits 976-1007)
		EsgotoDrenagem: []StatusBitDefinition{
			// Word 61 (Bits 976-991)
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 0, Description: "RESERVA"},
			{Name: "REARME_AUTOMATICO_ARRANCADOR_BE1", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 1, Description: "REARME AUTOMATICO ARRANCADOR BE1"},
			{Name: "REARME_AUTOMATICO_ARRANCADOR_BE2", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 2, Description: "REARME AUTOMATICO ARRANCADOR BE2"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 3, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 4, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 5, Description: "RESERVA"},
			{Name: "DISPARO_DISJUNTOR_QB_ALIMENTACAO_BOIAS_QEBED2", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 6, Description: "DISPARO DISJUNTOR QB ALIMENTAÇÃO BOIAS QEBED2"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 7, Description: "RESERVA"},
			{Name: "BOMBA_ESGOTO_1_LIGADA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 8, Description: "BOMBA ESGOTO 1 LIGADA"},
			{Name: "BOMBA_ESGOTO_2_LIGADA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 9, Description: "BOMBA ESGOTO 2 LIGADA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 10, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 11, Description: "RESERVA"},
			{Name: "BOTAO_ACEITACAO_AVARIAS_PREMIDO", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 12, Description: "BOTÃO ACEITAÇÃO DE AVARIAS PREMIDO"},
			{Name: "ORDEM_MARCHA_BOMBA_ESGOTO_1", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 13, Description: "ORDEM MARCHA BOMBA ESGOTO 1"},
			{Name: "ORDEM_MARCHA_BOMBA_ESGOTO_2", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 14, Description: "ORDEM MARCHA BOMBA ESGOTO 2"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 61, BitIndex: 15, Description: "RESERVA"},

			// Word 62 (Bits 992-1007)
			{Name: "FALTA_FORCA_MOTRIZ_3X400VAC_BE1", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 0, Description: "FALTA FORÇA MOTRIZ 3X400VAC BE1"},
			{Name: "FALTA_FORCA_MOTRIZ_3X400VAC_BE2", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 1, Description: "FALTA FORÇA MOTRIZ 3X400VAC BE2"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 2, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 3, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 4, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 5, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 6, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 7, Description: "RESERVA"},
			{Name: "SISTEMA_EM_MANUAL", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 8, Description: "SISTEMA EM EM MANUAL"},
			{Name: "SISTEMA_EM_AUTOMATICO", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 9, Description: "SISTEMA EM AUTOMATICO"},
			{Name: "SISTEMA_DESLIGADO_FORA_SERVICO", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 10, Description: "SISTEMA DESLIGADO - FORA SERVIÇO"},
			{Name: "BOMBA_ESGOTO_1_FORA_SERVICO_POR_OPERADOR", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 11, Description: "BOMBA ESGOTO 1 FORA DE SERVIÇO POR OPERADOR"},
			{Name: "BOMBA_ESGOTO_2_FORA_SERVICO_POR_OPERADOR", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 12, Description: "BOMBA ESGOTO 2 FORA DE SERVIÇO POR OPERADOR"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 13, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 14, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "RG_EVENTO_ESGOTO_DRENAGEM", WordIndex: 62, BitIndex: 15, Description: "RESERVA"},
		},

		// RESERVA EVENTOS GERAL - Word 64 (Bits 1024-1040)
		ReservaEventos: []StatusBitDefinition{
			// Word 64 (Bits 1024-1040)
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 0, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 1, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 2, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 3, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 4, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 5, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 6, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 7, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 8, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 9, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 10, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 11, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 12, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 13, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 14, Description: "RESERVA"},
			{Name: "RESERVA", Equipment: "Reserva Eventos Geral", WordIndex: 64, BitIndex: 15, Description: "RESERVA"},
		},
	}
}

// ProcessEventBits preenche os valores dos bits de eventos baseado nos dados do PLC
func ProcessEventBits(bitExtractor *BitExtractor) *EventBitsStructure {
	eventDefs := GetEventBitDefinitions()
	
	// Preencher valores para cada equipamento
	for i := range eventDefs.Enchimento {
		bit := &eventDefs.Enchimento[i]
		bit.Value = bitExtractor.GetSingleBit("event", bit.WordIndex, bit.BitIndex)
	}
	
	for i := range eventDefs.Esvaziamento {
		bit := &eventDefs.Esvaziamento[i]
		bit.Value = bitExtractor.GetSingleBit("event", bit.WordIndex, bit.BitIndex)
	}
	
	for i := range eventDefs.PortaJusante {
		bit := &eventDefs.PortaJusante[i]
		bit.Value = bitExtractor.GetSingleBit("event", bit.WordIndex, bit.BitIndex)
	}
	
	for i := range eventDefs.PortaMontante {
		bit := &eventDefs.PortaMontante[i]
		bit.Value = bitExtractor.GetSingleBit("event", bit.WordIndex, bit.BitIndex)
	}
	
	for i := range eventDefs.ComandoEclusa {
		bit := &eventDefs.ComandoEclusa[i]
		bit.Value = bitExtractor.GetSingleBit("event", bit.WordIndex, bit.BitIndex)
	}
	
	for i := range eventDefs.EsgotoDrenagem {
		bit := &eventDefs.EsgotoDrenagem[i]
		bit.Value = bitExtractor.GetSingleBit("event", bit.WordIndex, bit.BitIndex)
	}
	
	for i := range eventDefs.ReservaEventos {
		bit := &eventDefs.ReservaEventos[i]
		bit.Value = bitExtractor.GetSingleBit("event", bit.WordIndex, bit.BitIndex)
	}
	
	return eventDefs
}